config/routes.rb
Rails.application.routes.draw do
  get 'help/contact_us', to: 'assist_messages#new'
  get 'help', to: 'instructions#index'
  get 'help/legacies', to: 'instructions#legacies'
  get 'help/memories', to: 'instructions#memories'
  get 'help/accounts', to: 'instructions#accounts'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'users/index'
  get 'signup', to: 'users#new'
  get 'users/edit' 
  get 'users/show'  
  get 'home/index'

  root 'legacies#index'
  resources :memories
  resources :legacies do 
    resources :comments
  end
  resources :users
  resources :charges
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :instructions
  resources :assist_messages
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  def index
  end

  def legacies
  end

  def memories
  end

  def accounts
  end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/views/instructions/accounts.html.erb
<title>Help - Accounts</title>
<h1>How to create and activate your account:</h1>
<p>You will only need to create and activate your account if you are wanting to create a legacy, or if you would like to comment on others legacy files. On our menu, we seperate the account options from the site options. Your account options are all on the top left corner of the website.</p> 

<ol>
	<li>Click on the <strong><%= link_to "Sign Up", signup_path %></strong> link.</li>
	<li>Enter your <strong>Name</strong>, <strong>Avatar</strong>, <strong>Email</strong>, <strong>Password</strong>, and <strong>Password Confirmation</strong> - Avatar is just an image file that is added by clicking the Choose File button.</li>
	<li>Click <button>Create Account</button></li>
	<li>Go to your email inbox to get your Activation email.</li>
	<li>Click the link inside the email Activate.</li>
	<li>After you click the activate, your account is created and activated. <strong>Your all set!</strong></li>
</ol>

app/views/instructions/index.html.erb
<title>My Legacy Files - Help</title>
<h1>Help Desk</h1>
<p>Here you will find answers to questions that you may have, if you do not see your question here, then please use the form below to ask your question. We will get back to any requests as soon as possible. Thank you.</p>

<ol>
	<li><%= link_to "How do I create and activate my account?", help_accounts_path %></li>
	<li><%= link_to "How do I create a legacy?", help_legacies_path %></li>
	<li><%= link_to "What are memories, and how do I create use them?", help_memories_path %></li>
</ol>
<p>If your not seeing the answer you are looking for, please <%= link_to "Contact us", help_contact_us_path %> with your question.</p>

app/views/instructions/legacies.html.erb
<title>Help - Create a legacy</title>
<h1>How to create a legacy</h1>
<p>After you have created and activated your account and log in, it takes you to your <strong>Profile</strong> page.</p>
<p><%= image_tag("profile_page_on_account_creation.png") %></p>
<ol>
	<li>Click on "New Legacy" link to create your new legacy. - This link will only be available to click if you have an unused legacy.</li>
	<li>Using the form that is displayed, enter the <strong>Name</strong>, a <strong>Photo</strong>, <strong>Birth Day</strong>, <strong>Passed On</strong> date, <strong>State</strong>, <strong>County</strong>, <strong>City</strong>, and under the <strong>About</strong> you will enter information that will describe who your legacy was. In many cases, this can just be their obituary. You may want to use their obituary and other information that you feel is relevant to describe who the legacy was.</li>
	<li>Click the <button>Create Legacy</button></li>
	<li>At this point, you will be directed to the legacy file you just created.</li>
</ol>
<p><strong>Note:</strong> When you are on your legacy files page, you will see a QR Code on the left side, underneath where the photo and information is. This is the image that has to be printed to add to a headstone or memorial. It is best to laminate these if you are printing it yourself.</p>

app/views/instructions/memories.html.erb
<title>Help - Create Memories</title>
<h1>Memories</h1>
<p>Memories on Legacy files are just photos of the legacy, or photos of family members. You can use any photo that has a memory involving the legacy.</p>
<p>Some memories are even pictures that may have been taken out the funeral itself.</p>
<p>To add memories to a legacy, you would have to start by being on the legacy page.</p>
<p><strong>Max number of memories per legacy - </strong> Each legacy is allowed 10 memories.</p>


<ol>
	<li>On the top right corner of the legacy page, will be the link to "Add memory". Click this link.</li>
	<li>You will then be directed to the legacies memories page. On this page, choose a file to upload.</li>
	<li>Click on the button <button>Create Memory</button></li>
</ol>