config/routes.rb
Rails.application.routes.draw do
  get 'help/contact_us', to: 'assist_messages#new'
  get 'help', to: 'instructions#index'
  get 'help/legacies', to: 'instructions#legacies'
  get 'help/memories', to: 'instructions#memories'
  get 'help/accounts', to: 'instructions#accounts'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'users/index'
  get 'signup', to: 'users#new'
  get 'users/edit' 
  get 'users/show'  
  get 'home/index'

  root 'legacies#index'
  resources :memories
  resources :legacies do 
    resources :comments
  end
  resources :users
  resources :charges
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :instructions
  resources :assist_messages
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :reset_token

	before_save :downcase_email
  before_create :create_activation_digest

	validates :name, presence: true, length: {maximum: 50}
  validates :avatar, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, presence: true, length: {maximum: 255},
		format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: { case_sensitive: false }
	

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	has_many :legacies
  has_many :comments
  has_many :assist_messages

	has_attached_file :avatar



	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  #downcases email incase user adds case to it
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #Set reset digest token
  def create_reset_token
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  #Sends reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  # def authenticated?(remember_token)
  #   BCrypt::Password.new(remember_digest).is_password?(remember_token)
  # end
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_logged_in?, only: [:update, :edit]
  before_action :get_available_legacies, only: [:show]

  def index
  	@users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    if current_user
      flash[:notice] = "You cannot sign up, you are currently logged in."
      redirect_to current_user
    end
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    @user.increment!(:legacy_count)
  	if @user.save
      UserMailer.account_activation(@user).deliver_now
  		flash[:notice] = "Thank you for signing up at Legacy Files. Please check your email to activate your account."
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
    unless current_user == @user || current_user.super?
      flash[:notice] = "You can only edit your own profile."
      redirect_to @user
  end

    end
  def update
    @user = User.find(params[:id])

    respond_to do |format|
    if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    unless current_user == @user || current_user.admin?
      flash[:notice] = "You can only delete your own profile."
      redirect_to users_url
      return
    end
    User.find(params[:id]).destroy
    flash[:notice] = "User deleted"
    redirect_to users_url
  end

  def show
  	@user = User.find(params[:id])
    @legacy_price =  "$89.99"
    @sale_price = "Sale price: $18.00"
    if current_user.try(:super?)
      @unactivated = User.where('activated = ?', false)
      @unactivated_expired = @unactivated.where('date(created_at) <= ?', 3.days.ago)
    end 
  end

private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :admin, :legacy_count)
	end	

  def user_logged_in?
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end

  def get_available_legacies
    @user = User.find(params[:id])
    unless @user.legacy_count.nil?
      @avalaible = @user.legacies.count - @user.legacy_count
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
	<%= simple_form_for(@user, html: { multipart: true }) do |user| %>
    	<%= render 'shared/error_messages' %>
		<%= user.input :name %>
		<%= user.input :avatar, as: :file %>
		<%= user.input :email %>
		<%= user.input :password %>
		<%= user.input :password_confirmation %>
		<% if current_user.try(:super?) %>
			<%= user.input :admin %>
			<%= user.input :moderator %>
			<%= user.input :super %>
		<% end %>
		<%= user.submit "Create Account", :onclick => "alert('When you account is successfully create, an activation email will be sent to the email you have used on your account. Please activate your account to be able to log in.')" %>
	<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Edit Profile</title>
</head>
<body>
<div class="content_body">
	<h1>Update your profile</h1>
	<%= simple_form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		<%= f.input :name %>
		<%= f.input :email %>
		<%= f.input :password %>
		<%= f.input :password_confirmation %>
		<%= image_tag @user.avatar.url, size: "180x200" %>
		<%= f.input :avatar, as: :file %>
		<% if current_user.try(:super?) %>
			<table>
				<td><%= f.input :admin %></td>
				<td><%= f.input :super %></td>			
			</table>
			<%= f.input :legacy_count %>
		<% end %>
		<%= f.submit %>
	<% end %>
</div><div class="clear"></div>
</body>
</html>

app/views/users/index.html.erb
<title>Legacy Files Users</title>
<%= will_paginate(:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'pagination-sm') %>
    <table>
      <thead>
        <tr>
          <th>Photo</th>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
          	<% if user.avatar.present? %>
            	<td><%= image_tag user.avatar.url, size: 40 %></td>
            <% else %>
            	<td><img src="../assets/nopic.png" height="40" width="40" /></td>
            <% end %>
            <td><%= link_to user.name, user %></td>
            <% if current_user.try(:super?) %>
              <td><%= link_to 'Edit', edit_user_path(user) %></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/users/new.html.erb
<div class="content_body">
	<%= render 'form' %>
</div>
<div class="clear"></div>

app/views/users/show.html.erb
<title>
<% if current_user == @user %>
	My Profile
<% else %>
	<%= @user.name %>'s Profile
<% end %>
</title>
<div class="row">
	<div class="col-sm-3">
		<% if @user.avatar.present? %>
			<%= image_tag @user.avatar.url, size: "180x200" %>
		<% else %>
			<img src="../assets/nopic.png" height="200" width="180" />
		<% end %>
		<br>
		<% if current_user.try(:admin?) %>
			<% if @user.activated? %>
				<strong>Activated</strong>
			<% else %>
				<strong>Not Activated</strong>
			<% end %>
		<% end %>
	</div>
	<div class="col-sm-6">
		<% if current_user == @user  %>
			<h1>My Legacies</h1>
			<p>You currently have <%= pluralize(current_user.legacies.count, "legacy") %>. 
				<% unless @user.legacies.count.nil? || @user.legacy_count.nil? %>
				You currently have <%= pluralize(current_user.legacy_count - current_user.legacies.count, "legacy") %> available to use.
				<% end %>
			</p> 
			<% unless @user.legacies.count.nil? || @user.legacy_count.nil? %>
				<% if current_user.legacy_count - current_user.legacies.count >= 1 %>
					<p>You can click the "New Legacy" link below to create a new legacy.</p> 
					<p><%= link_to 'New Legacy', new_legacy_path %></p>
				<% end %>
			<% else %><p>You can purchase a new legacy to create one: <%= @legacy_price %>, but you can get it for the sale price now, which is 80% off the regular price, <strong><%= @sale_price %></strong> now by selecting the button to the right, "Pay with card".</p>
			<% end %>

			<table>
			  <thead>
			    <tr>
			      <th>Photo</th>
			      <th>Name</th>
			      <th>State</th>
			      <th>About</th>
			      <th colspan="3"></th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @user.legacies.each do |legacy| %>
			      <tr>
			        <% if legacy.photo.present? %>
			          <td><%= link_to image_tag(legacy.photo.url, size: "40x40"), legacy %></td>
			        <% else %>
			          <td><a href="/legacies/<%= legacy.id %>"><img src="assets/nopic.png" height="40" width="40"></td>
			        <% end %>

			        <td style="width: 120px;"><%= legacy.name %></td>
			        <td><%= legacy.state %></td>
			        <td><%= legacy.about.truncate(15) %></td>
			        <% if current_user.try(:admin) %>
			          <td><%= link_to 'Show', legacy %></td>
			          <td><%= link_to 'Edit', edit_legacy_path(legacy) %></td>
			          <td><%= link_to 'Destroy', legacy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			        <% end %>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		<% else %>
			<h1>My Legacies</h1>
			<table>
			  <thead>
			    <tr>
			      <th>Photo</th>
			      <th>Name</th>
			      <th>State</th>
			      <th>About</th>
			      <th colspan="3"></th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @user.legacies.each do |legacy| %>
			      <tr>
			        <% if legacy.photo.present? %>
			          <td><%= link_to image_tag(legacy.photo.url, size: "40x40"), legacy %></td>
			        <% else %>
			          <td><a href="/legacies/<%= legacy.id %>"><img src="../assets/nopic.png" height="40" width="40"></td>
			        <% end %>

			        <td style="width: 120px;"><%= legacy.name %></td>
			        <td><%= legacy.state %></td>
			        <td><%= legacy.about.truncate(50) %></td>
			        <% if current_user.try(:admin) %>
			          <td><%= link_to 'Show', legacy %></td>
			          <td><%= link_to 'Edit', edit_legacy_path(legacy) %></td>
			          <td><%= link_to 'Destroy', legacy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			        <% end %>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		<% end %>
		<% if current_user.try(:super?) %>
			<%= link_to 'Edit', edit_user_path(@user) %>
		<% end %>
		<%= link_to 'Back', :back %>

		<% if current_user.try(:super?) %>
			<br><br>
			<hr>
			<h1>Expired Accounts</h1>
			<br><br>
			<table>
			  <thead>
			    <tr>
			      <th>Photo</th>
			      <th>Name</th>
			      <th>Email</th>
			      <th colspan="3"></th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @unactivated_expired.each do |user| %>
			      <tr>
			        <% if user.avatar.present? %>
			          <td><%= link_to image_tag(user.avatar.url, size: "40x40"), user %></td>
			        <% else %>
			          <td><a href="/users/<%= user.id %>"><img src="../assets/nopic.png" height="40" width="40"></td>
			        <% end %>

			        <td style="width: 120px;"><%= user.name %></td>
			        <td><%= user.email %></td>
					<td><%= link_to 'Edit', edit_user_path(user) %></td>
					<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>	
		<% end %>
	</div>
	<div class="col-sm-3">
		<% if current_user == @user %>
			<%= form_tag charges_path do %>
			  <article>
			    <% if flash[:error].present? %>
			      <div id="error_explanation">
			        <p><%= flash[:error] %></p>
			      </div>
			    <% end %>
			    <label class="amount">
			    	<% if current_user.legacy_count.nil? %>
			    		<span>
			    			<strong>You do not have any legacy pages yet.</strong> To purchase a legacy page (<strong><%= @sale_price %></strong>), you just have to click the "Pay with card" button below.
			    		</span>

			    	<% else %>
			    		<span>
			    		<strong>You currently have <%= current_user.legacy_count %> Legacy page(s).</strong> To purchase another legacy, just click the "Pay with card" button.</span>
			    	<% end %>
			    </label>
			  </article>

			  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
			          data-description="Add Legacy to account"
			          data-amount="7999"
			          data-locale="auto"></script>
			<% end %>
		<% end %>
	</div>	
</div>

<div class="clear"></div>