config/routes.rb
Rails.application.routes.draw do
  get 'help/contact_us', to: 'assist_messages#new'
  get 'help', to: 'instructions#index'
  get 'help/legacies', to: 'instructions#legacies'
  get 'help/memories', to: 'instructions#memories'
  get 'help/accounts', to: 'instructions#accounts'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'users/index'
  get 'signup', to: 'users#new'
  get 'users/edit' 
  get 'users/show'  
  get 'home/index'

  root 'legacies#index'
  resources :memories
  resources :legacies do 
    resources :comments
  end
  resources :users
  resources :charges
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :instructions
  resources :assist_messages
end

app/models/legacy.rb
class Legacy < ApplicationRecord
	has_attached_file :photo
	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
	belongs_to :user
	has_many :memories
	has_many :comments

	# def self.search(search)
	#   where("lower(name) LIKE ? OR lower(state) LIKE ? OR lower(city) LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
	# end

	def self.search(search)
	  where("name ILIKE ? OR state ILIKE ? OR city ILIKE ? OR county ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
	end
end

app/controllers/legacies_controller.rb
class LegaciesController < ApplicationController
  before_action :set_legacy, only: [:show, :edit, :update, :destroy]
  before_action :user_logged_in?, only: [:edit, :update, :create, :new, :destroy]

  # GET /legacies
  # GET /legacies.json
  def index
    @legacies = Legacy.paginate(page: params[:page], per_page: 5)
    if params[:search]
      @legacies = Legacy.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 8)
    else
      @legacies = Legacy.paginate(page: params[:page], per_page: 7)
    end
  end

  # GET /legacies/1
  # GET /legacies/1.json
  def show
    @age = age(Legacy.find(params[:id]).born_on)
    @comments = Comment.where(legacy_id: @legacy).order("created_at DESC")
  end

  # GET /legacies/new
  def new
    unless current_user.try(:super?)
      if current_user.legacies.count >= current_user.legacy_count
        flash[:notice] = "You cannot create any more legacies, without purchasing more legacy pages."
        redirect_to current_user
      end
    end
    @legacy = current_user.legacies.build
  end

  # GET /legacies/1/edit
  def edit
    @legacy = Legacy.find(params[:id])

    unless current_user.id == @legacy.user_id || current_user.super?
      redirect_to @legacy
      flash[:notice] = "Cannot edit Legacies that do not belong to your account."
    end
  end

  # POST /legacies
  # POST /legacies.json
  def create
    @legacy = current_user.legacies.build(legacy_params)

    respond_to do |format|
      if @legacy.save
        format.html { redirect_to @legacy, notice: 'Legacy was successfully created.' }
        format.json { render :show, status: :created, location: @legacy }
      else
        format.html { render :new }
        format.json { render json: @legacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legacies/1
  # PATCH/PUT /legacies/1.json
  def update
    @legacy.age = age(@legacy.born_on)
    respond_to do |format|
      if @legacy.update(legacy_params)
        format.html { redirect_to @legacy, notice: 'Legacy was successfully updated.' }
        format.json { render :show, status: :ok, location: @legacy }
      else
        format.html { render :edit }
        format.json { render json: @legacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legacies/1
  # DELETE /legacies/1.json
  def destroy
    @legacy.destroy
    respond_to do |format|
      format.html { redirect_to legacies_url, notice: 'Legacy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legacy
      @legacy = Legacy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legacy_params
      params.require(:legacy).permit(:name, :age, :born_on, :passed_on, :country, :state, :county, :city, :about, :photo)
    end

    #Get age without entering an age, with date of birth and date of death
    def age(dob)
      died = Legacy.find(params[:id]).passed_on
      now = Time.now.utc.to_date
      if died != nil
        died.year - dob.year - ((died.month > dob.month || (died.month == dob.month && died.day >= dob.day)) ? 0 : 1)
      else
        now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
      end
    end

    def user_logged_in?
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_path
      end
    end
end

app/helpers/legacies_helper.rb
module LegaciesHelper
end

app/views/legacies/_edit_form.html.erb
<%= simple_form_for(@legacy) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.input :born_on, as: :date, start_year: 1700, end_year: Date.today.year, order: [:month, :day, :year] %>
    <%= f.input :passed_on, as: :date, start_year: 1700, end_year: Date.today.year, order: [:month, :day, :year] %>
    <%= f.input("country", only: ["AG", "AU", "BS", "BZ", "CA", "DM", "GD", "GY", "IE", "JM", "NZ", "KN", "LC", "VC", "TT", "GB", "US"], selected: ["US"], :disabled => true) %>
    <%= f.select :state, us_states %>
    <%= f.input :county %>
    <%= f.input :city %>
    <%= f.input :about %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/legacies/_form.html.erb
<%= simple_form_for(@legacy) do |f| %>
  <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
     <%= f.input :born_on, as: :date, start_year: 1700, end_year: Date.today.year, order: [:month, :day, :year] %>
     <%= f.input :passed_on, as: :date, start_year: 1700, end_year: Date.today.year, order: [:month, :day, :year] %>
    <%= f.input("country", only: ["AG", "AU", "BS", "BZ", "CA", "DM", "GD", "GY", "IE", "JM", "NZ", "KN", "LC", "VC", "TT", "GB", "US"], selected: ["US"], :disabled => true) %>
    <%= f.label :state %>
    <%= f.select :state, us_states %>
    <%= f.input :county %>
    <%= f.input :city %>
    <%= f.input :about %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/legacies/edit.html.erb
<title>Edit - <%= @legacy.name %>'s Legacy</title>
<h1>Editing Legacy</h1>

<%= render 'edit_form', legacy: @legacy %>

<%= link_to 'Show', @legacy %> |
<%= link_to 'Back', legacies_path %>		

app/views/legacies/index.html.erb
<title>Legacy Files</title>
<div class="row">
  <div class="col-sm-5">
    <title>Legacy Files</title>
    <h3>Legacy Files is pleased to bring you the future of memorializing the ones we love.</h3>
    <p>
      My Legacy Files has been working toward a better way of preserving the memories and legacies of our loved ones. We now have a place where loved ones can be honored and remembered forever. Future generations will know exactly who we were and what we did to get to where they are in the future.
    </p>
    <h3>How it works:</h3>
    <p>
      With Legacy Files, we allow users to build and maintain the legacy of their loved ones as they see fit. You are able to create your own user account for free. With a user account, you are able to create your own legacy pages, and leave comments on others legacy pages. Legacies contains information you and friends can add about your loved one, such as: thier obituary, photos, comments by friends and relatives. Currently, you will get to create a free legacy page, like the ones you see on the right, when you create and activate a new account. <% unless logged_in? %> So <%= link_to("Sign Up", new_user_path) %> now, for your free legacy!<% end %>
    </p>  
  </div>
  <div class="col-sm-5">
  <h1>A Few of Our Legacies</h1>
  <table>
    <thead>
      <tr>
        <th>Photo</th>
        <th>Name</th>
        <th>Born on</th>
        <th>Passed on</th>
        <th>State</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @legacies.each do |legacy| %>
        <tr>
          <% if legacy.photo.present? %>
            <td><%= link_to image_tag(legacy.photo.url, size: "40x40"), legacy %></td>
          <% else %>
            <td><a href="/legacies/<%= legacy.id %>"><img src="../assets/nopic.png" height="40" width="40"></a></td>
          <% end %>

          <td><%= legacy.name %></td>
          <td><%= legacy.born_on.strftime("%m-%d-%Y") %></td>
          <% unless legacy.passed_on == nil %>
              <td><%= legacy.passed_on.strftime("%m-%d-%Y") %></td>
          <% else %>
              <td>Still Alive</td>
          <% end %>
          <td><%= legacy.state %></td>
          <% if current_user.try(:admin) %>
            <td><%= link_to 'Show', legacy %></td>
            <td><%= link_to 'Edit', edit_legacy_path(legacy) %></td>
            <td><%= link_to 'Destroy', legacy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br />
  <%= will_paginate(:renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'pagination-sm') %>
  </div>  
</div>
<div class="clear"></div>

app/views/legacies/new.html.erb
<title>Create a Legacy</title>
<h1>New Legacy</h1>

<%= render 'form', legacy: @legacy %>

<%= link_to 'Back', legacies_path %>

app/views/legacies/show.html.erb
<head><%= render 'qrcode' %>
  <title><%= @legacy.name %>'s Legacy</title>
</head>
    <div class="row">
      <div class="col-sm-2">
        <% if @legacy.photo.present? %>
          <%= image_tag @legacy.photo.url, size: "180x200" %><br />
        <% else %>
          <img src="../assets/nopic.png" height="200" width="180">
        <% end %>
        <strong><%= @legacy.name %></strong><br />
        Age: <%= @age %><br />
        Born on:<br /><%= @legacy.born_on.strftime("%a, %b %d, %Y") %><br />
        <% if @legacy.passed_on.present? %>
          Passed on:<br /><%= @legacy.passed_on.strftime("%a, %b %d, %Y") %><br />
        <% end %>
        <% if @legacy.country.present? %>
          Country: <%= @legacy.country %><br />
        <% end %>
        <% if @legacy.state.present? %>
          State: <%= @legacy.state %><br />
        <% end %>
        <% if @legacy.county.present? %>
          County: <%= @legacy.county %><br />
        <% end %>
        <% if @legacy.city.present? %>
          City: <%= @legacy.city %><br />
        <% end %>
        <% if current_user == @legacy.user || current_user.try(:admin?) %>
        <div id="qrcode" style="width:100px; height:100px; margin-top:15px;"></div>
        <% end %>
      </div>
      <div class="col-sm-6">
        <% unless !@legacy.about.present? %>
            <% if @legacy.passed_on.present? %>
              <strong>Who <%= @legacy.name %> was:</strong>
            <% else %>
              <strong>Who <%= @legacy.name %> is:</strong>
            <% end %>
            <p><%= @legacy.about %></p> 
        <% end %>
        <% if current_user.try(:admin?) %>
            <%= link_to 'Edit', edit_legacy_path(@legacy) %> |
        <% end %>
        <%= link_to 'Back', legacies_path %>
        <p>
          <strong>Legacy created by:</strong><br />
          <% if @legacy.user.avatar.present? %>
            <td><%= image_tag @legacy.user.avatar.url, size: 40 %></td>
          <% else %>
            <td><img src="/assets/nopic.png" height="40" width="40" /></td>
          <% end %>
          <%= link_to @legacy.user.name, @legacy.user %>
        </p>
        <%= render 'comments/comments' %>
      </div>
      <div class="memories">
        <div class="col-sm-3">
        <% if current_user == @legacy.user %>
          <% if @legacy.memories.count <= 0 %>
            Currently your legacy has no memories. To get the legacy page to show images here, click this "New Memory" link below.<br /> 
          <% end %>
          <%= link_to "New Memory", new_memory_path(legacy_id: @legacy.id) %><br />
        <% end %>
        <% if @legacy.memories.present? %>
          <% @legacy.memories.each do |memory| %>
            <td><%= image_tag memory.photo.url %></td>
              <script type="text/javascript">
                var currentIndex = 0;
                var allImages = document.getElementsByTagName("img");

                function showImage(index) {
                  for (var i=0; i<allImages.length; i++) { 
                    var img = allImages.item(i);
                    img.className = 'hidden';
                  }
                  
                  var currentImage = allImages.item(index);
                  currentImage.className = 'showing';
                }

                (function slideshow() {
                  showImage(currentIndex);
                  currentIndex = (currentIndex + 1) % allImages.length;
                  setTimeout(slideshow, 10000);
                })();
              </script>
          <% end %>
        <% end %>
      </div>
    </div>  
    <div class="clear"></div>
    <script type="text/javascript">
      var qrcode = new QRCode(document.getElementById("qrcode"), {
        width : 100,
        height : 100
      });
      function makeCode () {    
        
        qrcode.makeCode(window.location.href);
      }
      makeCode();
      $("#text").
        on("blur", function () {
          makeCode();
        }).
        on("keydown", function (e) {
          if (e.keyCode == 13) {
            makeCode();
          }
        });
    </script>
    </div>