config/routes.rb
Rails.application.routes.draw do
  get 'help/contact_us', to: 'assist_messages#new'
  get 'help', to: 'instructions#index'
  get 'help/legacies', to: 'instructions#legacies'
  get 'help/memories', to: 'instructions#memories'
  get 'help/accounts', to: 'instructions#accounts'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'users/index'
  get 'signup', to: 'users#new'
  get 'users/edit' 
  get 'users/show'  
  get 'home/index'

  root 'legacies#index'
  resources :memories
  resources :legacies do 
    resources :comments
  end
  resources :users
  resources :charges
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :instructions
  resources :assist_messages
end

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer font-small stylish-color-dark pt-4 mt-4" style="background-color: #bdbdbd;">

    <!--Footer Links-->
    <div class="container text-center text-md-left">
        <div class="row">

            <!--First column-->
            <div class="col-md-4">
                <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">My Legacy Files</h5>
                <div class="fb-like" data-href="https://facebook.com/mylegacyfiles" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
                <br><br>
                <p>Here at <a href="https://www.mylegacyfiles.com">MyLegacyFiles.com</a> we know that life is the most precious asset we have. We also know how terrible it is when someone we care about loses theirs. It takes time, but the pain does get easier to manage. In the <strong>Grieving?</strong> section on these links, there are some websites that may be able to help you through this time.</p>
            </div>
            <!--/.First column-->

            <hr class="clearfix w-100 d-md-none">

            <!--Second column-->
            <div class="col-md-2 mx-auto">
                <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Grieving?</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="https://www.wikihow.com/Deal-With-Death" target="_blank">Mourning Loss</a>
                    </li>
                    <li>
                        <a href="http://www.chicagotribune.com/lifestyles/sc-deal-with-death-first-time-family-0216-20160211-story.html" target="_blank">Chicago Tribune</a>
                    </li>
                    <li>
                        <a href="https://www.washingtontimes.com/news/2017/may/1/health-how-deal-death-loss-grief-bereavement/" target="_blank">Stages of Grief</a>
                    </li>
                    <li>
                        <a href="https://www.betterhelp.com/helpme/?utm_source=AdWords&utm_medium=Search_PPC_c&utm_term=help+with+grief_e&utm_content=42801117506&network=g&placement=&target=&matchtype=e&utm_campaign=849308107&ad_type=text&adposition=1t1&gclid=Cj0KCQjw8MvWBRC8ARIsAOFSVBVAfW4vVl4wL4phSgh73GUVceXJzK_Kwu2oUUACr24Z12sUJpAXZSgaAmRyEALw_wcB&not_found=1&gor=helpme&klove_go_exp=y&klove=1">Online Support</a>
                    </li>
                </ul>
            </div>
            <!--/.Second column-->

           <hr class="clearfix w-100 d-md-none">

            <!--Third column-->
            <div class="col-md-2 mx-auto">
                <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Our Site</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="/help">Help</a>
                    </li>
                    <li>
                        <a href="/help/contact_us">Contact us</a>
                    </li>
                </ul>
            </div>
            <!--/.Third column-->

            <hr class="clearfix w-100 d-md-none">

            <!--Fourth column-->
            <div class="col-md-2 mx-auto">
                <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Partners</h5>
                <ul class="list-unstyled">
                    <li>
                        <a href="/help/contact_us">Become a partner</a>
                    </li>
                </ul>
            </div>
            <!--/.Fourth column-->
        </div>
    </div>
    <!--/.Footer Links-->
<% unless logged_in? %>
    <hr>

    <!--Call to action-->
    <div class="text-center py-3">
        <ul class="list-unstyled list-inline mb-0">
            <li class="list-inline-item">
                <h5 class="mb-1">Register for free</h5>
            </li>
            <li class="list-inline-item">
                <a href="/signup" class="btn btn-danger btn-rounded">Sign up!</a>
            </li>
        </ul>
    </div>
    <!--/.Call to action-->
<% end %>
    <hr>

    <!--Social buttons-->
    <div class="text-center">
        <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
                <a class="btn-floating btn-lg btn-fb mx-1" href="https://www.facebook.com/MyLegacyFiles/" style="color: black;" target="_blank">
                    <i class="fa fa-facebook"> </i>
                </a>
            </li>
            <li class="list-inline-item">
                <a class="btn-floating btn-lg btn-tw mx-1" href="https://twitter.com/MyLegacyFiles" target="_blank" style="color: black;">
                    <i class="fa fa-twitter"> </i>
                </a>
            </li>
        </ul>
    </div>
    <!--/.Social buttons-->

    <!--Copyright-->
    <div class="footer-copyright py-3 text-center">
        © 2018 Copyright:
        <a href="https://www.mylegacyfiles.com"> MyLegacyFiles.com </a>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->
                      

app/views/layouts/_header.html.erb
<div class="container_top">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <% if logged_in? %>
      <li style="float: left;"><%= link_to "Log out", logout_path %></li>
      <li style="float: left;"><%= link_to "Settings", edit_user_path(current_user) %></li>
      <li style="float: left;"><%= link_to "Profile", current_user %></li>
      <% if current_user.try(:admin?) && @helps.present? %>
        <li><%= link_to "Help(#{@helps_count})", assist_messages_path %></li>
      <% else %>
        <% if @unread.present? %>
          <li style="color: red;"><%= link_to "Ticket(#{@unread.count})", assist_messages_path %></li>
        <% end %>
      <% end %>
    <% else %>
      <li style="float: left;"><%= link_to "Sign Up", signup_path %></li>
      <li style="float: left;"><%= link_to "Log in", login_path %></li>
    <% end %>
    <div class="title"><h1>My Legacy Files</h1></div>
  </ul>
<div class="clear"></div>
</div><div class="white_space"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  </head>
<body>
<div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
	<%= render 'layouts/header' %>
    <div id="search">
      <%= form_tag(legacies_path, :method => "get", id: "search-form") do %>
          <%= submit_tag "Search", :name => nil %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Legacies", :size => 10 %>
      <% end %>      
    </div><div class="clear"></div>
	<div class="container_body">
    <p><%= notice %></p>
    <p style="color: red;"><%= alert %></p>
		<%= yield %>
	</div>
  <div class="footer">
    <%= render 'layouts/footer' %>
  </div>
  <div class="clear"></div>
  <% debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>